if ((typeof(basis$Initial$)) == "undefined") {basis$Initial$ = {};
};
(function(){basis$Initial$.en$Fail$45 = new String("Fail");
basis$Initial$.posInf$52 = Infinity;
basis$Initial$.negInf$53 = -Infinity;
basis$Initial$.ln10$62 = Math.log(10.0);
basis$Initial$.NaN$63 = Math.sqrt(-1.0);
basis$Initial$.localoffset$67 = SmlPrims.localoffset();
basis$Initial$.fail_strftime$68 = [basis$Initial$.en$Fail$45,"strftime"];
basis$Initial$.initial_realtime$72 = SmlPrims.getrealtime();
basis$Initial$.initial_rutime$73 = [0,0,0,0,0,0];
var printer$74 = [function(s$77){return document.write(s$77);
}];
basis$Initial$.printer_set$89 = function(p$92){return (printer$74[0] = p$92,0);
};
basis$Initial$.printer_get$93 = function(v$95){return printer$74[0];
};
return 0;
})();
