if ((typeof(basis$IO$)) == "undefined") {basis$IO$ = {};
};
(function(){basis$IO$.eq_buffer_mode$84 = function(v$86,v$87){switch (v$86) { case 0: {switch (v$87) { case 0: {return true;
 break; }default: {return false;
} };
 break; }case 1: {switch (v$87) { case 1: {return true;
 break; }default: {return false;
} };
 break; }case 2: {switch (v$87) { case 2: {return true;
 break; }default: {return false;
} };
 break; } };
};
basis$IO$.en$Io$50 = new String("Io");
basis$IO$.en$BlockingNotSupported$51 = new String("BlockingNotSupported");
basis$IO$.exn$BlockingNotSupported$51 = [basis$IO$.en$BlockingNotSupported$51];
basis$IO$.en$NonblockingNotSupported$52 = new String("NonblockingNotSupported");
basis$IO$.exn$NonblockingNotSupported$52 = [basis$IO$.en$NonblockingNotSupported$52];
basis$IO$.en$RandomAccessNotSupported$53 = new String("RandomAccessNotSupported");
basis$IO$.exn$RandomAccessNotSupported$53 = [basis$IO$.en$RandomAccessNotSupported$53];
basis$IO$.en$ClosedStream$54 = new String("ClosedStream");
basis$IO$.exn$ClosedStream$54 = [basis$IO$.en$ClosedStream$54];
return 0;
})();
