if ((typeof(tools$Crash$)) == "undefined") {tools$Crash$ = {};
};
(function(){tools$Crash$.en$CRASH$45 = new String("CRASH");
tools$Crash$.exn$CRASH$45 = [tools$Crash$.en$CRASH$45];
tools$Crash$.impossible$50 = function(msg$53){var msg$54 = "Impossible: " + msg$53;
basis$General$.print$156(msg$54 + "\n");
throw tools$Crash$.exn$CRASH$45;
};
tools$Crash$.assert$57 = function(v$69,v$126){if (v$126) {return 0;
} else {var msg$66 = "Assert fails: " + v$69;
basis$General$.print$156(msg$66 + "\n");
throw tools$Crash$.exn$CRASH$45;
};
};
tools$Crash$.unimplemented$71 = function(msg$74){var msg$75 = "Unimplemented: " + msg$74;
basis$General$.print$156(msg$75 + "\n");
throw tools$Crash$.exn$CRASH$45;
};
return 0;
})();
