if ((typeof(basics$DFInfo$)) == "undefined") {basics$DFInfo$ = {};
};
(function(){basics$DFInfo$.eq_DFInfo$109 = function(v$111,v$112){switch (v$111[0]) { case 0: {switch (v$112[0]) { case 0: {return true;
 break; }default: {return false;
} };
 break; }case 1: {switch (v$112[0]) { case 1: {return true;
 break; }default: {return false;
} };
 break; }case 2: {switch (v$112[0]) { case 2: {return true;
 break; }default: {return false;
} };
 break; }case 3: {switch (v$112[0]) { case 3: {return true;
 break; }default: {return false;
} };
 break; }case 4: {switch (v$112[0]) { case 4: {return true;
 break; }default: {return false;
} };
 break; }case 5: {switch (v$112[0]) { case 5: {var v$113 = v$111[1];
var v$114 = v$112[1];
return tools$FinMap$.eq_map$644(function(v$126){return syntax_objects$Ident$.eq_id$237(v$126[0],v$126[1]);
},function(v$127){return basics$InfixBasis$.eq_InfixEntry$208(v$127[0],v$127[1]);
},[v$113,v$114]);
 break; }default: {return false;
} };
 break; }case 6: {switch (v$112[0]) { case 6: {return true;
 break; }default: {return false;
} };
 break; }case 7: {switch (v$112[0]) { case 7: {return true;
 break; }default: {return false;
} };
 break; }case 8: {switch (v$112[0]) { case 8: {return true;
 break; }default: {return false;
} };
 break; } };
};
basics$DFInfo$.string$59 = function(v$62){switch (v$62[0]) { case 1: {return "UNITEXP";
 break; }case 2: {return "TUPLE";
 break; }case 8: {return "CASE";
 break; }case 6: {return "IF_df";
 break; }case 3: {return "ORELSE_df";
 break; }case 7: {return "FUN_df";
 break; }case 0: {return "VALIT_df";
 break; }case 4: {return "INFIX_df";
 break; }default: {return "INFIX_BASIS";
} };
};
basics$DFInfo$.layout$81 = function(x$118){var v$124;
switch (x$118[0]) { case 1: {v$124 = "UNITEXP";
 break; }case 2: {v$124 = "TUPLE";
 break; }case 8: {v$124 = "CASE";
 break; }case 6: {v$124 = "IF_df";
 break; }case 3: {v$124 = "ORELSE_df";
 break; }case 7: {v$124 = "FUN_df";
 break; }case 0: {v$124 = "VALIT_df";
 break; }case 4: {v$124 = "INFIX_df";
 break; }default: {v$124 = "INFIX_BASIS";
} };
return [1,v$124];
};
return 0;
})();
